#!/bin/bash

BASE_OPS="O0
O1
O2
O3"

EXTRA_OPS="unroll-loops
no-unroll-loops
optimize-sibling-calls
dce
if-conversion
schedule-insns"

DISABLE="auto-inc-dec 
cprop-registers 
dce 
defer-pop 
delayed-branch 
dse 
guess-branch-probability 
if-conversion2 
if-conversion 
ipa-pure-const 
ipa-reference 
merge-constants
split-wide-types 
tree-builtin-call-dce 
tree-ccp 
tree-ch 
tree-copyrename 
tree-dce 
tree-dominator-opts 
tree-dse 
tree-fre 
tree-sra 
tree-ter 
unit-at-a-time
thread-jumps 
align-functions  
align-jumps 
align-loops  
align-labels 
caller-saves 
crossjumping 
cse-follow-jumps  
cse-skip-blocks 
delete-null-pointer-checks 
expensive-optimizations 
gcse  
gcse-lm  
inline-small-functions 
indirect-inlining 
optimize-sibling-calls 
peephole2 
reorder-blocks  
reorder-functions 
rerun-cse-after-loop  
sched-interblock  
sched-spec 
schedule-insns  
schedule-insns2 
strict-aliasing 
strict-overflow 
tree-switch-conversion 
tree-pre 
tree-vrp
inline-functions
unswitch-loops
predictive-commoning
gcse-after-reload
vect-cost-model
ipa-cp-clone"
